sudo: false

language: haskell
ghc:
  - "8.0"

install:
  - cd QuantumHaskell-notation && cabal install --dry-run --only-dependencies --enable-tests
  - cd QuantumHaskell-mathlib && cabal install --dry-run --only-dependencies --enable-tests QuantumHaskell-mathlib/

script:
  - cd QuantumHaskell-notation && cabal configure --enable-tests && cabal build && cabal test 
  - cd QuantumHaskell-mathlib && cabal configure --enable-tests && cabal build && cabal test 

notifications:
  email: false
