sudo: false

language: haskell
ghc:
  - "8.0"

before_install:
  - cabal install hpc-coveralls

install:
  - cd QuantumHaskell-notation/ && cabal install --only-dependencies --enable-tests && cd ..
  - cd QuantumHaskell-mathlib/ && cabal install --only-dependencies --enable-tests && cd ..

script:
  - cd QuantumHaskell-notation/ && cabal configure --enable-coverage --enable-tests && cabal build && cabal test && cd ..
  - cd QuantumHaskell-mathlib/ && cabal configure --enable-coverage --enable-tests && cabal build && cabal test

after_script:
  - cabal sandbox init && cabal install hpc-coveralls
  - .cabal-sandbox/bin/hpc-coveralls QuantumHaskell-notation/test/notation-test.hs

notifications:
  email: false
